### ISSUE TITLE
Documentation for "single library" endpoint appears incomplete

### ISSUE THREAD

**Issue by tchamberlin** [adsabs/biblib-service#168]
The API documentation (https://ui.adsabs.harvard.edu/help/api/api-docs.html#put-/biblib/documents/-library_id-) for the "single library" endpoint (`/biblib/libraries/{library_id}`) appears incomplete. It indicates only a path parameter, `library_id`. However, in practice it appears to support the same URL parameters as the "view all libraries for a given user" endpoint (https://ui.adsabs.harvard.edu/help/api/api-docs.html#get-/biblib/libraries)

Also, the maximum rows that can be requested is not documented. `rows=500` appears to work, and is the maximum allowed by the public web page (`https://ui.adsabs.harvard.edu/public-libraries/<library_id>`), so I'm assuming that is a reasonable number to paginate by

**Comment by tjacovich** [comment]
@tchamberlin you are correct that `/biblib/libraries/{library_id}` does take additional query arguments. They are not quite consistent with `/biblib/libraries` because the `sort` options available for libraries are not the same as those for individual documents. Instead, `/biblib/libraries/{library_id}` uses a subset of the arguments from the search endpoints. We have added the available fields to the documentation along with a note that additional details can be found in the documentation for search. The maximum number of rows is also the same as the maximum returnable by search, which is currently 2000. Thank you for catching this and helping us improve the quality of our documentation.
