### ISSUE TITLE
Displaying library ownership

### ISSUE THREAD

**Issue by jonnybazookatone** [adsabs/biblib-service#46]
@aholachek brought up a good request: When presenting libraries, the owner should be displayed in some form. 
 
Currently, the only option would be:

  * owner : the email of the owner of the library

I had the following problems with this:

  * Do users really want to display their email to other people? Guaranteed if it's a public profile they would not want to show it - but then how do you show who owns the library. 
  * Even if you let some people look at it, do you really want them to see your e-mail too?
  * This is circumvented with an identifier which is not the e-mail address. 
  * Or the user can be given the option to show/unshow their e-mail address - but I think this is adding more logic for something that is the wrong direction. Also, if they unshow, how is it identified in a sane way?

Given it would not only involve private libraries, I leave this open for other people's comments/decisions.

**Comment by jonnybazookatone** [comment]
One temporary choice is to display just the content before the @ symbol in the e-mail address, which does not require people to give more information.

Regardless of how this is implemented, this requires another end point similar to the e-mail resolver (issue adsabs/adsws/issues/58), whereby the e-mail address (or identifier) is returned given the API accounts user UID.

**Comment by aaccomazzi** [comment]
From a practical perspective, I think that having a public library without a minimum of profile data also publicly available makes little sense.  And we know that we will need to support a user's "public profile" if they decide to have one.  This is what I suggest:

1. If the user's name is known (because they entered in in their profile), display it.
2. Instead of the email address, use a nickname (what appears before the @ sign)
3. Link the nickname to the user's profile URL (TBD) which, if the user chooses to make public, would provide additional information; if it isn't public, then we just show a very terse message.

**Comment by jonnybazookatone** [comment]
OK. Currently, 2. is implemented by PR #52. Numbers 1 and 3 will need to be addressed when they get implemented within the accounts. I will close this issue and open other relevant ones at a later date.
